Homework3
made-mlops-2022/Vladimir_Shaposhnikov pull request #3
Opened 2022-12-04 20:20 UTC by Volodimirich

**Все существующие DAG:** 
![image](https://user-images.githubusercontent.com/55362016/205512911-b4b925a8-c954-41e8-9702-46023cf0016d.png)

**Генерация данных**: 
![image](https://user-images.githubusercontent.com/55362016/205513180-d0b73d00-9b9b-439e-b110-da865b036f7a.png)

**Предсказание**:
![image](https://user-images.githubusercontent.com/55362016/205513152-10109063-42b6-4763-9535-c83e3407a668.png)

**Полный цикл (получение модели, предикт, валдиация)**
![image](https://user-images.githubusercontent.com/55362016/205513141-5d68a3a3-0754-485a-88c4-6ba596327a11.png)

**_Настроенная почта с уведомлениями:_**
![image](https://user-images.githubusercontent.com/55362016/205513207-07ea194c-d957-4175-8ac2-4a5de8733aaa.png)

Поднимите airflow локально, используя docker compose (можно использовать из примера https://github.com/made-ml-in-prod-2021/airflow-examples/)

- [X] Реализуйте dag, который генерирует данные для обучения модели (генерируйте данные -- можете использовать как генератор синтетики из первой дз, так и что-то из датасетов sklearn). Вам важно проэмулировать ситуации постоянно поступающих данных (5 баллов) - использовал make_classification из sklearn.datasets (5 баллов)

- [X] Реализуйте dag, который обучает модель еженедельно, используя данные за текущий день. В вашем пайплайне должно быть как минимум 4 стадии, но дайте волю своей фантазии =) (10 баллов) - сделал 4 стадии: split -> preprocess -> train -> validate (10 баллов)

- [X] Реализуйте dag, который использует модель ежедневно (5 баллов) - сделал predict даг (5 баллов)

- [X] Все даги реализованы только с помощью DockerOperator (пример[ https://github.com/made-ml-in-prod-2021/airflow-examples/blob/main/dags/11_docker.py](https://github.com/made-ml-in-prod-2021/airflow-examples/blob/main/dags/11_docker.py)). По технике, вы можете использовать такую же структуру как в примере, пакуя в разные докеры скрипты. (10 баллов)

- [X] Традиционно, самооценка (1 балл)

Дополнительная часть

- [X] Реализуйте сенсоры на то, что данные готовы для дагов тренировки и обучения  3 балла)
- [ ] Протестируйте ваши даги[ https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html) (5 баллов)
- [ ] В docker compose так же настройте поднятие mlflow и запишите туда параметры обучения, метрики и артефакт (модель) (5 баллов)
- [ ] Вместо пути в airflow variables используйте API Mlflow Model Registry. Даг для инференса должен подхватывать последнюю продакшен модель (5 баллов)

- [X] Настройте alert в случае падения дага[ https://www.astronomer.io/guides/error-notifications-in-airflow](https://www.astronomer.io/guides/error-notifications-in-airflow) (3 балла)

2022-12-07 08:47 UTC, bulaevvi requested changes
Нижние скриншоты нормальные, но на верхнем (общем) видно, что второй и третий даги падали (судя по красным кружочкам). Надо разобраться, почему они падали, и добиться такого результата, чтобы все выполнялось нормально

Обратите внимание, что в приведенном мною дискордовском примере падений не было https://discord.com/channels/681511874449244211/1011956997790380123/1049258596866727946

2022-12-07 10:25 UTC, bulaevvi commented
Прикрепите пожалуйста скриншоты прямо здесь, в комментариях, чтобы не сбивалась дата сабмита и не тратить времени на поиск файлов

2022-12-07 18:02 UTC, Volodimirich commented
> Нижние скриншоты нормальные, но на верхнем (общем) видно, что второй и третий даги падали (судя по красным кружочкам). Надо разобраться, почему они падали, и добиться такого результата, чтобы все выполнялось нормально
> 
> Обратите внимание, что в приведенном мною дискордовском примере падений не было https://discord.com/channels/681511874449244211/1011956997790380123/1049258596866727946


Здравствуйте, падение Дагов обусловлено моим дебагом во время выполнения задания (забыл почистить перед отправкой). Требуется подчистить и залить картинки заново? 
![telegram-cloud-photo-size-2-5217884669478027701-y](https://user-images.githubusercontent.com/55362016/206260551-b8de44ce-fa9d-4aaa-a913-375dff034ec3.jpg)

![telegram-cloud-photo-size-2-5217884669478027700-y](https://user-images.githubusercontent.com/55362016/206260452-fb73a365-da50-499b-af5e-73390c0e5e5a.jpg)

2022-12-08 04:07 UTC, bulaevvi commented
Если хотите без штрафа, то лучше верхнюю картинку переделать, чтобы было без падений, как в приведенном мною примере

2022-12-08 15:27 UTC, Volodimirich commented
> Если хотите без штрафа, то лучше общую картинку переделать, чтобы было без падений, как в приведенном мною примере

 Здравствуйте, прикрепляю картинку без падений

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/55362016/206485704-a983b2b6-d22b-4550-9809-a456dc612a05.png">

2022-12-09 04:30 UTC, bulaevvi approved these changes
Итого 37 баллов. Делайте merge

2022-12-09 14:15 UTC, Volodimirich commented
Если вы не возражаете, я сделаю мердж после проверки дз 2. Данную ветку я отнаследовался от ветки дз 2 и если я сделаю мердж, то пул реквест дз 2 пропадет

2022-12-10 06:15 UTC, bulaevvi commented
Ok

2022-12-19 21:36 UTC, merged